FROM python:latest

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY pipeline/extract_carbon.py .
COPY pipeline/common.py .
COPY config.py .
COPY constants.py .


EXPOSE 443

CMD python3 extract_carbon.py
