name: Build and Push Docker Images

on: [push, pull_request]

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Verify Environment Variables
      run: |
        echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
        echo "ECR_URL: ${{ secrets.ECR_URL }}"
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_URL: ${{ secrets.ECR_URL }}

    - name: Log in to AWS ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_URL: ${{ secrets.ECR_URL }}
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL

    - name: Make build_and_push.sh executable and run it
      run: |
        cd infrastructure
        chmod +x build_and_push.sh
        ./build_and_push.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_URL: ${{ secrets.ECR_URL }}

    - name: Logout from AWS ECR
      run: docker logout ${{ secrets.ECR_URL }}
