name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # Install the package using setup.py, which reads from requirements.txt if set up

    - name: Activate virtual environment and set up environment
      run: |
        source $(python -m site --user-site)/../bin/activate  # Activate the venv
        source ./add_root_to_path.sh  # Run the script after activation
        
    - name: Run tests
      run: |
        pytest  # Run tests directly with pytest
