### Workflow tests

# Looks like this is ignored by push unless you specificall add it:
#  git add .github/workflows/ci.yml; git commit -m "updated actions workflow"; git push


name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install --with dev

    - name: Set up environment
      run: |
        poetry run bash ./add_root_to_path.sh  # Run the script inside Poetry's virtual environment

    - name: Run tests
      run: |
        poetry run pytest