name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-use-pep517 -r requirements.txt  # Install dependencies from requirements.txt without using PEP 517
        pip install --no-use-pep517 -e .  # Install the package in editable mode using setup.py, avoiding PEP 517

    - name: Set up environment
      run: |
        source ./add_root_to_path.sh  # Run the script to modify PYTHONPATH

    - name: Run tests
      run: |
        pytest  # Run tests directly with pytest