name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        pip install -e .  # Install the package using setup.py, which reads from requirements.txt if set up

    - name: Set up environment
      run: |
        source ./add_root_to_path.sh  # Run the script to modify PYTHONPATH

    - name: Run tests
      run: |
        pytest  # Run tests directly with pytest
