name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Create and activate virtual environment
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the virtual environment

    - name: Install dependencies
      run: |
        pip install --upgrade pip  # Upgrade pip within the virtual environment
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        pip install -e .  # Install the package in editable mode using setup.py

    - name: Set up environment
      run: |
        source venv/bin/activate  # Ensure the virtual environment is active
        source ./add_root_to_path.sh  # Run the script to modify PYTHONPATH

    - name: Run tests
      run: |
        source venv/bin/activate  # Ensure the virtual environment is active
        pytest  # Run tests directly with pytest