name: Pytest Coverage

on: [push, pull_request]

jobs:
  upload-pytest-coverage:
    name: Generate and Upload Coverage Report for Pytest and Codecov
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies for Pytest-Cov
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt  # Install all dependencies, including pytest-cov

    - name: Set up environment
      run: |
        source venv/bin/activate
        export PYTHONPATH="$PYTHONPATH:$(pwd)"
        source ./add_root_to_path.sh

    - name: Generate Coverage Report
      run: |
        source venv/bin/activate
        pytest --cov=./ --cov-report=xml:coverage.xml  # Generate coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        flags: pytest
        name: pytest-coverage-report
        fail_ci_if_error: true
