name: Code Climate Coverage

on: [push, pull_request]

jobs:
  upload-code-climate-coverage:
    name: Generate and Upload Coverage Report for Code Climate
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies for Code Climate
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install coverage==4.4  # Install the version of coverage compatible with codeclimate-test-reporter
        pip install -r requirements.txt  # Install other dependencies

    - name: Set up environment
      run: |
        source venv/bin/activate
        export PYTHONPATH="$PYTHONPATH:$(pwd)"
        source ./add_root_to_path.sh

    - name: Generate Coverage Report
      run: |
        source venv/bin/activate
        pytest --cov=./ --cov-report=xml:coverage.xml  # Generate coverage.xml

    - name: Report to Code Climate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
      run: |
        source venv/bin/activate
        codeclimate-test-reporter < coverage.xml

    - name: Upload coverage to Codecov (optional, if you want to upload this report to Codecov as well)
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        flags: codeclimate
        name: code-coverage-report
        fail_ci_if_error: true
